= Policy Decision Point - Embedded

Cerbos Hub generates an embeddable version of policies - powered by WebAssembly - enabling authorization decision to be made on device, at edge or other environments where it is not possible to run a service. These bundles are generated through the CI/CD pipeline and are kept in sync with your policies on every change. These modules can be loaded into client applications via the Cerbos SDKs and handle authorization cehcks without the need to roundtrip to the backend service. Use cases such as showing and hiding UI elements on a webpage can be done all locally using the data avaliable in the page but still using the policies being served by the service instances.

== Implement an embedded policy decision point

=== Javascript

The Cerbos Lite Javascript SDK is designed to work with the embedded policy bundles generated by Cerbos Hub and exposes the same simple API interface for checking permissions.

To get started, install the package:

[source,bash]
----
npm install @cerbos/lite
----

In the application code, import the SDK and then download the bundle using fetch (or any other method you prefer). This will download the latest bundle and load it in. Cerbos Hub will generate a new bundle for each deployment label on every matching commit keeping policies in sync.

[source,typescript]
----
import { Lite as Cerbos } from "@cerbos/lite";

// Provide the URL to the label bundle from the Decision points page
const cerbos = new Cerbos(fetch("https://lite.cerbos.cloud/bundle?workspace=...&label=..."));

// The cerbos.checkResource() method can now be used to check permissions locally
await cerbos.isAllowed({
  principal: {
    id: "user@example.com",
    roles: ["USER"],
    attr: { tier: "PREMIUM" },
  },
  resource: {
    kind: "document",
    id: "1",
    attr: { owner: "user@example.com" },
  },
  action: "view",
}); // => true
----

.SDK support
****
Support for other SDKs and languages is coming soon
****
