= Policy Stores: CLI upload (Homebrew)

== Installation

`cerbosctl` binaries are available via Homebrew for simple installation on macOS. To install the `cerbosctl` CLI tool, run the following command:

[source,sh]
----
brew tap cerbos/tap
brew install cerbos
----

== Usage

The `cerbosctl` CLI tool can be used to upload policies to a Policy Store in Cerbos Hub. 

First generate a set of client credentials for the Policy Store in Cerbos Hub - you can do this in the **Client credentials** section in the UI. Make sure to select the `Read & Write` option when creating the credentials to allow uploading policies.

Then export the following environment variables with the values from the generated client credentials and the store ID:

[source,sh]
----
export CERBOS_HUB_CLIENT_ID=...
export CERBOS_HUB_CLIENT_SECRET=...
export CERBOS_HUB_STORE_ID=...
----

The following command uploads policy files from the current directory and replaces all the files in the store.

[source,sh]
----
cerbosctl hub store replace-files .
----

== Full CLI Reference
include::partial$cli-usage.adoc[]
