= Policy stores: CLI upload (npx)

== Installation

`cerbosctl` binaries are published to npm for easy installation. To install the `cerbosctl` CLI tool, run the following command:

[source,sh]
----
npm install -g cerbosctl
----

Alternatively, you can use `npx` to run the CLI without installing it globally.


== Usage

The `cerbosctl` CLI tool can be used to upload policies to a policy store in Cerbos Hub. 

First generate a set of client credentials for the policy store in Cerbos Hub - you can do this in the **Client credentials** section in the UI. Make sure to select the `Read & Write` option when creating the credentials to allow uploading policies.

Then export the following environment variables with the values from the generated client credentials and the store ID:

[source,sh]
----
export CERBOS_HUB_CLIENT_ID=...
export CERBOS_HUB_CLIENT_SECRET=...
export CERBOS_HUB_STORE_ID=...
----

The following command uploads policy files from the current directory and replaces all the files in the store.

=== via global NPM installation
[source,sh]
----
cerbosctl hub store replace-files .
----

=== via npx
[source,sh]
----
npx cerbosctl hub store replace-files .
----


== Full CLI Reference
include::partial$cli-usage.adoc[]
