= Release notes

== 2025-08-04

=== Usage dashboard
The new xref:cerbos:usage-dashboard.adoc[Usage Dashboard] provides comprehensive, real-time observability into your authorization service. It allows you to monitor key metrics, analyze trends, and gain insights into how your policies are being used across your organization.

=== API key lifecycle
Should an API become blocked due to misconfiguration, you can now unblock it directly from the API key list. 

== 2025-07-17

A major launch of the xref:cerbos:policy-stores.adoc[Policy Stores] feature in Cerbos Hub, which allows you to manage your policies across multiple environments and deployments. You can read more in the announcement blog post: https://www.cerbos.dev/blog/updated-cerbos-hub-complete-authorization-solution-for-your-identity-fabrics[Updated Cerbos Hub, the complete authorization solution for your Identity Fabric
,window=_blank].


== 2025-04-28

=== Organization deletion
You can now delete an organization in Cerbos Hub. To delete an organization, navigate to the organization settings page and click on the "Delete organization" button. Please note that this action is irreversible and will permanently delete all data associated with the organization.

== 2025-03-12

=== Playground
The effective derived roles for a user are now displayed in the playground when evaluating policies. This feature helps you understand which derived roles were activated for that user during that request.


=== Embedded Policy Decision Point
Time-based functions used in condition expressions such as `getHours` and `getMinutes` default to UTC unless the time zone is explicitly provided as an argument to the function. It's recommended to review your policies to make sure that time calculations use the correct time zone. Refer to xref:cerbos:policies:conditions.adoc#_timestamps[timestamps documentation] to identify the affected functions.


== 2025-02-26

=== Embedded Policy Decision Point

We’ve introduced support for capturing audit decision logs from the Cerbos Hub Embedded Policy Decision Points (ePDP) using the latest version of the https://github.com/cerbos/cerbos-sdk-javascript[Cerbos Javascript SDK]. This feature enables organizations to track and analyze authorization decisions made locally in embedded environments, ensuring complete visibility and auditability, without relying on a centralized PDP or Cerbos Hub.


== 2025-02-01

The Builds section of Cerbos Hub has been renamed Policies. The Policies section now includes all the features previously available in Builds, such as policy versioning, policy history, and policy deployment. The Builds section has been removed from the Cerbos Hub navigation.

== 2025-01-28

=== Playground
Added support for xref:cerbos:configuration:engine.adoc#_globals[globals] in playground engine settings. Global variables defined in the xref:playground.adoc[playground settings] are exposed to policy conditions via the `globals` object.


